import { defaultLayoutItems } from "./layoutItems";

export const LIBRARY_KEY = "label-template-library-v1";

export const builtInTemplateKeys = ["blank", "shipping", "cargo", "receiving", "return", "transfer", "pallet"];

const builtInTemplateTranslations = {
  shipping: {
    tr: { name: "Sevkiyat Etiketi", description: "Sevk ve dagitim surecleri icin genel cikis etiketi.", labelTitle: "SEVKIYAT ETIKETI" },
    en: { name: "Shipping Label", description: "General outbound label for shipping and distribution.", labelTitle: "SHIPPING LABEL" },
    de: { name: "Versandetikett", description: "Allgemeines Ausgangsetikett fur Versand und Distribution.", labelTitle: "VERSANDETIKETT" },
    es: { name: "Etiqueta de envio", description: "Etiqueta general de salida para envios y distribucion.", labelTitle: "ETIQUETA DE ENVIO" },
    fr: { name: "Etiquette d'expedition", description: "Etiquette generale pour l'expedition et la distribution.", labelTitle: "ETIQUETTE D'EXPEDITION" }
  },
  cargo: {
    tr: { name: "Kargo Etiketi", description: "Teslimat ve kurye akislarina uygun standart kargo duzeni.", labelTitle: "KARGO ETIKETI" },
    en: { name: "Cargo Label", description: "Standard cargo layout for delivery and courier flows.", labelTitle: "CARGO LABEL" },
    de: { name: "Frachtetikett", description: "Standardlayout fur Liefer- und Kurierablaufe.", labelTitle: "FRACHTETIKETT" },
    es: { name: "Etiqueta de carga", description: "Diseno estandar para flujos de entrega y mensajeria.", labelTitle: "ETIQUETA DE CARGA" },
    fr: { name: "Etiquette de fret", description: "Mise en page standard pour la livraison et le courrier.", labelTitle: "ETIQUETTE DE FRET" }
  },
  receiving: {
    tr: { name: "Mal Kabul Etiketi", description: "Gelen urun kontrol ve kabul operasyonlari icin net alanlar.", labelTitle: "MAL KABUL ETIKETI" },
    en: { name: "Receiving Label", description: "Clear fields for inbound inspection and receiving operations.", labelTitle: "RECEIVING LABEL" },
    de: { name: "Wareneingangsetikett", description: "Klare Felder fur Eingangskontrolle und Wareneingang.", labelTitle: "WARENEINGANGETIKETT" },
    es: { name: "Etiqueta de recepcion", description: "Campos claros para control y recepcion de productos.", labelTitle: "ETIQUETA DE RECEPCION" },
    fr: { name: "Etiquette de reception", description: "Champs clairs pour le controle et la reception.", labelTitle: "ETIQUETTE DE RECEPTION" }
  },
  return: {
    tr: { name: "Iade Etiketi", description: "Iade urunlerin ayristirma ve geri kabul surecleri icin.", labelTitle: "IADE ETIKETI" },
    en: { name: "Return Label", description: "For return sorting and reverse receiving workflows.", labelTitle: "RETURN LABEL" },
    de: { name: "Retourenetikett", description: "Fur Retouren-Sortierung und Rucknahmeprozesse.", labelTitle: "RETOURENETIKETT" },
    es: { name: "Etiqueta de devolucion", description: "Para clasificacion y recepcion de devoluciones.", labelTitle: "ETIQUETA DE DEVOLUCION" },
    fr: { name: "Etiquette de retour", description: "Pour le tri et la reception des retours.", labelTitle: "ETIQUETTE DE RETOUR" }
  },
  transfer: {
    tr: { name: "Depo Transfer Etiketi", description: "Depolar arasi urun hareketleri ve lokasyon transferleri icin.", labelTitle: "DEPO TRANSFER ETIKETI" },
    en: { name: "Warehouse Transfer Label", description: "For product movements and warehouse location transfers.", labelTitle: "WAREHOUSE TRANSFER LABEL" },
    de: { name: "Lagertransferetikett", description: "Fur Warenbewegungen und Standorttransfers im Lager.", labelTitle: "LAGERTRANSFERETIKETT" },
    es: { name: "Etiqueta de transferencia", description: "Para movimientos de productos y transferencias de ubicacion.", labelTitle: "ETIQUETA DE TRANSFERENCIA" },
    fr: { name: "Etiquette de transfert", description: "Pour les mouvements de produits et transferts d'emplacement.", labelTitle: "ETIQUETTE DE TRANSFERT" }
  },
  pallet: {
    tr: { name: "Palet Etiketi", description: "Palet takibi, saha sevki ve buyuk hacimli yuklemeler icin.", labelTitle: "PALET ETIKETI" },
    en: { name: "Pallet Label", description: "For pallet tracking, field shipping and large-volume loading.", labelTitle: "PALLET LABEL" },
    de: { name: "Palettenetikett", description: "Fur Palettenverfolgung und grossvolumige Verladungen.", labelTitle: "PALETTENETIKETT" },
    es: { name: "Etiqueta de palet", description: "Para seguimiento de palets y cargas de gran volumen.", labelTitle: "ETIQUETA DE PALET" },
    fr: { name: "Etiquette palette", description: "Pour le suivi des palettes et les chargements volumineux.", labelTitle: "ETIQUETTE PALETTE" }
  },
  blank: {
    tr: { name: "Bos Etiket", description: "Sifirdan baslamak icin temiz alan.", labelTitle: "BOS ETIKET" },
    en: { name: "Blank Label", description: "A clean space to start from scratch.", labelTitle: "BLANK LABEL" },
    de: { name: "Leeres Etikett", description: "Eine saubere Flache fur den Start von Grund auf.", labelTitle: "LEERES ETIKETT" },
    es: { name: "Etiqueta en blanco", description: "Un espacio limpio para empezar desde cero.", labelTitle: "ETIQUETA EN BLANCO" },
    fr: { name: "Etiquette vierge", description: "Un espace propre pour commencer a zero.", labelTitle: "ETIQUETTE VIERGE" }
  }
};

export const baseTemplates = {
  shipping: {
    name: "Sevkiyat Etiketi",
    description: "Sevk ve dağıtım süreçleri için genel çıkış etiketi.",
    brandName: "",
    labelTitle: "SEVKİYAT ETİKETİ",
    accentColor: "#f97316",
    backgroundColor: "#ffffff",
    textColor: "#111111",
    borderColor: "#111111",
    borderWidth: 2,
    fontFamily: "segoe",
    brandFontSize: 30,
    titleFontSize: 13,
    headingFontSize: 10,
    bodyFontSize: 13,
    density: "comfortable",
    showQr: true,
    showNote: true,
    highlightRecipient: true,
    showSender: true,
    showSenderAddress: true,
    showRecipient: true,
    showRecipientAddress: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    showDeliveryType: true,
    showBarcode: true,
    showBarcodeValue: true,
    showRulers: true,
    showCenterGuides: true,
    showGridOverlay: false,
    gridStepMm: 10,
    uiLanguage: "tr",
    printMode: "thermal",
    sheetLayout: "single",
    sizeCategory: "shipping",
    sizePreset: "shipping-102x152",
    labelWidthMm: 101.6,
    labelHeightMm: 152.4,
    pageMarginTop: 12,
    pageMarginSide: 12,
    sheetGap: 8,
    layoutItems: defaultLayoutItems,
    logoDataUrl: ""
  },
  cargo: {
    name: "Kargo Etiketi",
    description: "Teslimat ve kurye akışlarına uygun standart kargo düzeni.",
    brandName: "",
    labelTitle: "KARGO ETİKETİ",
    accentColor: "#0f766e",
    backgroundColor: "#f8fafc",
    textColor: "#0f172a",
    borderColor: "#0f766e",
    borderWidth: 3,
    fontFamily: "segoe",
    brandFontSize: 30,
    titleFontSize: 13,
    headingFontSize: 10,
    bodyFontSize: 13,
    density: "compact",
    showQr: true,
    showNote: false,
    highlightRecipient: true,
    showSender: true,
    showSenderAddress: true,
    showRecipient: true,
    showRecipientAddress: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    showDeliveryType: true,
    showBarcode: true,
    showBarcodeValue: true,
    showRulers: true,
    showCenterGuides: true,
    showGridOverlay: false,
    gridStepMm: 10,
    uiLanguage: "tr",
    printMode: "a4",
    sheetLayout: "single",
    sizeCategory: "shipping",
    sizePreset: "shipping-100x150",
    labelWidthMm: 100,
    labelHeightMm: 150,
    pageMarginTop: 12,
    pageMarginSide: 12,
    sheetGap: 6,
    layoutItems: defaultLayoutItems,
    logoDataUrl: ""
  },
  receiving: {
    name: "Mal Kabul Etiketi",
    description: "Gelen ürün kontrol ve kabul operasyonları için net alanlar.",
    brandName: "",
    labelTitle: "MAL KABUL ETİKETİ",
    accentColor: "#7c3aed",
    backgroundColor: "#fcfbff",
    textColor: "#2e1065",
    borderColor: "#8b5cf6",
    borderWidth: 2,
    fontFamily: "segoe",
    brandFontSize: 30,
    titleFontSize: 13,
    headingFontSize: 10,
    bodyFontSize: 13,
    density: "comfortable",
    showQr: true,
    showNote: true,
    highlightRecipient: false,
    showSender: true,
    showSenderAddress: true,
    showRecipient: true,
    showRecipientAddress: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    showDeliveryType: true,
    showBarcode: true,
    showBarcodeValue: true,
    showRulers: true,
    showCenterGuides: true,
    showGridOverlay: false,
    gridStepMm: 10,
    uiLanguage: "tr",
    printMode: "thermal",
    sheetLayout: "single",
    sizeCategory: "paper",
    sizePreset: "paper-a6",
    labelWidthMm: 105,
    labelHeightMm: 148,
    pageMarginTop: 10,
    pageMarginSide: 10,
    sheetGap: 6,
    layoutItems: defaultLayoutItems,
    logoDataUrl: ""
  },
  return: {
    name: "İade Etiketi",
    description: "İade ürünlerin ayrışma ve geri kabul süreçleri için.",
    brandName: "",
    labelTitle: "İADE ETİKETİ",
    accentColor: "#dc2626",
    backgroundColor: "#ffffff",
    textColor: "#111827",
    borderColor: "#111827",
    borderWidth: 4,
    fontFamily: "segoe",
    brandFontSize: 30,
    titleFontSize: 13,
    headingFontSize: 10,
    bodyFontSize: 13,
    density: "compact",
    showQr: true,
    showNote: true,
    highlightRecipient: true,
    showSender: true,
    showSenderAddress: true,
    showRecipient: true,
    showRecipientAddress: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    showDeliveryType: true,
    showBarcode: true,
    showBarcodeValue: true,
    showRulers: true,
    showCenterGuides: true,
    showGridOverlay: false,
    gridStepMm: 10,
    uiLanguage: "tr",
    printMode: "a4",
    sheetLayout: "single",
    sizeCategory: "shipping",
    sizePreset: "shipping-102x152",
    labelWidthMm: 101.6,
    labelHeightMm: 152.4,
    pageMarginTop: 8,
    pageMarginSide: 8,
    sheetGap: 4,
    layoutItems: defaultLayoutItems,
    logoDataUrl: ""
  },
  transfer: {
    name: "Depo Transfer Etiketi",
    description: "Depolar arası ürün hareketleri ve lokasyon transferleri için.",
    brandName: "",
    labelTitle: "DEPO TRANSFER ETİKETİ",
    accentColor: "#1d4ed8",
    backgroundColor: "#f8fbff",
    textColor: "#0f172a",
    borderColor: "#1d4ed8",
    borderWidth: 3,
    fontFamily: "segoe",
    brandFontSize: 30,
    titleFontSize: 13,
    headingFontSize: 10,
    bodyFontSize: 13,
    density: "compact",
    showQr: true,
    showNote: true,
    highlightRecipient: true,
    showSender: true,
    showSenderAddress: true,
    showRecipient: true,
    showRecipientAddress: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    showDeliveryType: true,
    showBarcode: true,
    showBarcodeValue: true,
    showRulers: true,
    showCenterGuides: true,
    showGridOverlay: false,
    gridStepMm: 10,
    uiLanguage: "tr",
    printMode: "a4",
    sheetLayout: "single",
    sizeCategory: "shipping",
    sizePreset: "shipping-102x152",
    labelWidthMm: 101.6,
    labelHeightMm: 152.4,
    pageMarginTop: 10,
    pageMarginSide: 10,
    sheetGap: 6,
    layoutItems: defaultLayoutItems,
    logoDataUrl: ""
  },
  pallet: {
    name: "Palet Etiketi",
    description: "Palet takibi, saha sevki ve büyük hacimli yüklemeler için.",
    brandName: "",
    labelTitle: "PALET ETİKETİ",
    accentColor: "#0f766e",
    backgroundColor: "#ffffff",
    textColor: "#111827",
    borderColor: "#0f172a",
    borderWidth: 4,
    fontFamily: "segoe",
    brandFontSize: 30,
    titleFontSize: 13,
    headingFontSize: 10,
    bodyFontSize: 13,
    density: "compact",
    showQr: true,
    showNote: true,
    highlightRecipient: true,
    showSender: true,
    showSenderAddress: true,
    showRecipient: true,
    showRecipientAddress: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    showDeliveryType: true,
    showBarcode: true,
    showBarcodeValue: true,
    showRulers: true,
    showCenterGuides: true,
    showGridOverlay: false,
    gridStepMm: 10,
    uiLanguage: "tr",
    printMode: "a4",
    sheetLayout: "single",
    sizeCategory: "shipping",
    sizePreset: "shipping-100x150",
    labelWidthMm: 100,
    labelHeightMm: 150,
    pageMarginTop: 10,
    pageMarginSide: 10,
    sheetGap: 6,
    layoutItems: defaultLayoutItems,
    logoDataUrl: ""
  }
};

export const blankTemplate = {
  name: "Boş Etiket",
  description: "Sıfırdan başlamak için temiz alan.",
  brandName: "",
  labelTitle: "SHIPPING LABEL",
  accentColor: "#f97316",
  backgroundColor: "#ffffff",
  textColor: "#111111",
  borderColor: "#111111",
  borderWidth: 2,
  fontFamily: "segoe",
  brandFontSize: 30,
  titleFontSize: 13,
  headingFontSize: 10,
  bodyFontSize: 13,
  density: "comfortable",
  showQr: true,
  showNote: true,
  highlightRecipient: false,
  showSender: true,
  showSenderAddress: true,
  showRecipient: true,
  showRecipientAddress: true,
  showOrderNo: true,
  showReference: true,
  showWeight: true,
  showDistance: true,
  showDeliveryTime: true,
  showDeliveryType: true,
  showBarcode: true,
  showBarcodeValue: true,
  showRulers: true,
  showCenterGuides: true,
  showGridOverlay: false,
  gridStepMm: 10,
  uiLanguage: "tr",
  printMode: "thermal",
  sheetLayout: "single",
  sizeCategory: "shipping",
  sizePreset: "shipping-102x152",
  labelWidthMm: 101.6,
  labelHeightMm: 152.4,
  pageMarginTop: 12,
  pageMarginSide: 12,
  sheetGap: 8,
  layoutItems: defaultLayoutItems,
  logoDataUrl: ""
};

export function getLocalizedBuiltInTemplate(key, language = "tr") {
  const base = key === "blank" ? blankTemplate : baseTemplates[key];
  if (!base) {
    return null;
  }

  const localized = builtInTemplateTranslations[key]?.[language]
    || builtInTemplateTranslations[key]?.en
    || builtInTemplateTranslations[key]?.tr
    || {};

  return {
    ...base,
    name: localized.name || base.name,
    description: localized.description || base.description,
    labelTitle: localized.labelTitle || base.labelTitle
  };
}

export const defaultContent = {
  senderName: "",
  senderAddress: "",
  recipientName: "",
  recipientAddress: "",
  orderNo: "",
  reference: "",
  weightValue: "",
  weightUnit: "KG",
  distanceValue: "",
  distanceUnit: "KM",
  deliveryTime: "",
  deliveryType: "",
  deliveryWindow: "",
  barcodeText: "",
  note: "",
  customFields: []
};

export function buildInitialForm(language = "tr") {
  const shippingTemplate = getLocalizedBuiltInTemplate("shipping", language) || baseTemplates.shipping;
  return {
    templateName: shippingTemplate.name,
    ...shippingTemplate,
    ...defaultContent
  };
}
