export const LIBRARY_KEY = "label-template-library-v1";

export const builtInTemplateKeys = ["blank", "shipping", "cargo", "receiving", "return", "transfer", "pallet"];

export const baseTemplates = {
  shipping: {
    name: "Sevkiyat Etiketi",
    description: "Sevk ve dagitim surecleri icin genel cikis etiketi.",
    brandName: "",
    labelTitle: "SEVKIYAT ETIKETI",
    accentColor: "#f97316",
    backgroundColor: "#ffffff",
    textColor: "#111111",
    borderColor: "#111111",
    borderWidth: 2,
    density: "comfortable",
    showQr: true,
    showNote: true,
    highlightRecipient: true,
    showSender: true,
    showSenderAddress: true,
    showRecipient: true,
    showRecipientAddress: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    showDeliveryType: true,
    showBarcode: true,
    showBarcodeValue: true,
    showRulers: true,
    showCenterGuides: true,
    showGridOverlay: false,
    gridStepMm: 10,
    uiLanguage: "tr",
    printMode: "thermal",
    sheetLayout: "single",
    sizeCategory: "shipping",
    sizePreset: "shipping-102x152",
    labelWidthMm: 101.6,
    labelHeightMm: 152.4,
    pageMarginTop: 12,
    pageMarginSide: 12,
    sheetGap: 8,
    logoDataUrl: ""
  },
  cargo: {
    name: "Kargo Etiketi",
    description: "Teslimat ve kurye akislarina uygun standart kargo duzeni.",
    brandName: "",
    labelTitle: "KARGO ETIKETI",
    accentColor: "#0f766e",
    backgroundColor: "#f8fafc",
    textColor: "#0f172a",
    borderColor: "#0f766e",
    borderWidth: 3,
    density: "compact",
    showQr: true,
    showNote: false,
    highlightRecipient: true,
    showSender: true,
    showSenderAddress: true,
    showRecipient: true,
    showRecipientAddress: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    showDeliveryType: true,
    showBarcode: true,
    showBarcodeValue: true,
    showRulers: true,
    showCenterGuides: true,
    showGridOverlay: false,
    gridStepMm: 10,
    uiLanguage: "tr",
    printMode: "a4",
    sheetLayout: "single",
    sizeCategory: "shipping",
    sizePreset: "shipping-100x150",
    labelWidthMm: 100,
    labelHeightMm: 150,
    pageMarginTop: 12,
    pageMarginSide: 12,
    sheetGap: 6,
    logoDataUrl: ""
  },
  receiving: {
    name: "Mal Kabul Etiketi",
    description: "Gelen urun kontrol ve kabul operasyonlari icin net alanlar.",
    brandName: "",
    labelTitle: "MAL KABUL ETIKETI",
    accentColor: "#7c3aed",
    backgroundColor: "#fcfbff",
    textColor: "#2e1065",
    borderColor: "#8b5cf6",
    borderWidth: 2,
    density: "comfortable",
    showQr: true,
    showNote: true,
    highlightRecipient: false,
    showSender: true,
    showSenderAddress: true,
    showRecipient: true,
    showRecipientAddress: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    showDeliveryType: true,
    showBarcode: true,
    showBarcodeValue: true,
    showRulers: true,
    showCenterGuides: true,
    showGridOverlay: false,
    gridStepMm: 10,
    uiLanguage: "tr",
    printMode: "thermal",
    sheetLayout: "single",
    sizeCategory: "paper",
    sizePreset: "paper-a6",
    labelWidthMm: 105,
    labelHeightMm: 148,
    pageMarginTop: 10,
    pageMarginSide: 10,
    sheetGap: 6,
    logoDataUrl: ""
  },
  return: {
    name: "Iade Etiketi",
    description: "Iade urunlerin ayrisma ve geri kabul surecleri icin.",
    brandName: "",
    labelTitle: "IADE ETIKETI",
    accentColor: "#dc2626",
    backgroundColor: "#ffffff",
    textColor: "#111827",
    borderColor: "#111827",
    borderWidth: 4,
    density: "compact",
    showQr: true,
    showNote: true,
    highlightRecipient: true,
    showSender: true,
    showSenderAddress: true,
    showRecipient: true,
    showRecipientAddress: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    showDeliveryType: true,
    showBarcode: true,
    showBarcodeValue: true,
    showRulers: true,
    showCenterGuides: true,
    showGridOverlay: false,
    gridStepMm: 10,
    uiLanguage: "tr",
    printMode: "a4",
    sheetLayout: "single",
    sizeCategory: "shipping",
    sizePreset: "shipping-102x152",
    labelWidthMm: 101.6,
    labelHeightMm: 152.4,
    pageMarginTop: 8,
    pageMarginSide: 8,
    sheetGap: 4,
    logoDataUrl: ""
  },
  transfer: {
    name: "Depo Transfer Etiketi",
    description: "Depolar arasi urun hareketleri ve lokasyon transferleri icin.",
    brandName: "",
    labelTitle: "DEPO TRANSFER ETIKETI",
    accentColor: "#1d4ed8",
    backgroundColor: "#f8fbff",
    textColor: "#0f172a",
    borderColor: "#1d4ed8",
    borderWidth: 3,
    density: "compact",
    showQr: true,
    showNote: true,
    highlightRecipient: true,
    showSender: true,
    showSenderAddress: true,
    showRecipient: true,
    showRecipientAddress: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    showDeliveryType: true,
    showBarcode: true,
    showBarcodeValue: true,
    showRulers: true,
    showCenterGuides: true,
    showGridOverlay: false,
    gridStepMm: 10,
    uiLanguage: "tr",
    printMode: "a4",
    sheetLayout: "single",
    sizeCategory: "shipping",
    sizePreset: "shipping-102x152",
    labelWidthMm: 101.6,
    labelHeightMm: 152.4,
    pageMarginTop: 10,
    pageMarginSide: 10,
    sheetGap: 6,
    logoDataUrl: ""
  },
  pallet: {
    name: "Palet Etiketi",
    description: "Palet takibi, saha sevki ve buyuk hacimli yuklemeler icin.",
    brandName: "",
    labelTitle: "PALET ETIKETI",
    accentColor: "#0f766e",
    backgroundColor: "#ffffff",
    textColor: "#111827",
    borderColor: "#0f172a",
    borderWidth: 4,
    density: "compact",
    showQr: true,
    showNote: true,
    highlightRecipient: true,
    showSender: true,
    showSenderAddress: true,
    showRecipient: true,
    showRecipientAddress: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    showDeliveryType: true,
    showBarcode: true,
    showBarcodeValue: true,
    showRulers: true,
    showCenterGuides: true,
    showGridOverlay: false,
    gridStepMm: 10,
    uiLanguage: "tr",
    printMode: "a4",
    sheetLayout: "single",
    sizeCategory: "shipping",
    sizePreset: "shipping-100x150",
    labelWidthMm: 100,
    labelHeightMm: 150,
    pageMarginTop: 10,
    pageMarginSide: 10,
    sheetGap: 6,
    logoDataUrl: ""
  }
};

export const blankTemplate = {
  name: "Bos Etiket",
  description: "Sifirdan baslamak icin temiz alan.",
  brandName: "",
  labelTitle: "SHIPPING LABEL",
  accentColor: "#f97316",
  backgroundColor: "#ffffff",
  textColor: "#111111",
  borderColor: "#111111",
  borderWidth: 2,
  density: "comfortable",
  showQr: true,
  showNote: true,
  highlightRecipient: false,
  showSender: true,
  showSenderAddress: true,
  showRecipient: true,
  showRecipientAddress: true,
  showOrderNo: true,
  showReference: true,
  showWeight: true,
  showDistance: true,
  showDeliveryTime: true,
  showDeliveryType: true,
  showBarcode: true,
  showBarcodeValue: true,
  showRulers: true,
  showCenterGuides: true,
  showGridOverlay: false,
  gridStepMm: 10,
  uiLanguage: "tr",
  printMode: "thermal",
  sheetLayout: "single",
  sizeCategory: "shipping",
  sizePreset: "shipping-102x152",
  labelWidthMm: 101.6,
  labelHeightMm: 152.4,
  pageMarginTop: 12,
  pageMarginSide: 12,
  sheetGap: 8,
  logoDataUrl: ""
};

export const defaultContent = {
  senderName: "",
  senderAddress: "",
  recipientName: "",
  recipientAddress: "",
  orderNo: "",
  reference: "",
  weightValue: "",
  weightUnit: "KG",
  distanceValue: "",
  distanceUnit: "KM",
  deliveryTime: "",
  deliveryType: "",
  deliveryWindow: "",
  barcodeText: "",
  note: ""
};

export function buildInitialForm() {
  return {
    templateName: baseTemplates.shipping.name,
    ...baseTemplates.shipping,
    ...defaultContent
  };
}
