export const LIBRARY_KEY = "label-template-library-v1";

export const builtInTemplateKeys = ["shipping", "cargo", "receiving", "return", "transfer", "pallet"];

export const presetSizes = {
  "4x6": { width: 101.6, height: 152.4 },
  "100x150": { width: 100, height: 150 },
  a6: { width: 105, height: 148 },
  custom: null
};

export const baseTemplates = {
  shipping: {
    name: "Sevkiyat Etiketi",
    description: "Sevk ve dagitim surecleri icin genel cikis etiketi.",
    brandName: "S4IN",
    labelTitle: "SEVKIYAT ETIKETI",
    accentColor: "#f97316",
    backgroundColor: "#ffffff",
    textColor: "#111111",
    borderColor: "#111111",
    borderWidth: 2,
    density: "comfortable",
    showQr: true,
    showNote: true,
    highlightRecipient: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    printMode: "thermal",
    sheetLayout: "single",
    sizePreset: "4x6",
    labelWidthMm: 101.6,
    labelHeightMm: 152.4,
    pageMarginTop: 12,
    pageMarginSide: 12,
    sheetGap: 8,
    logoDataUrl: ""
  },
  cargo: {
    name: "Kargo Etiketi",
    description: "Teslimat ve kurye akislarina uygun standart kargo duzeni.",
    brandName: "CARGO",
    labelTitle: "KARGO ETIKETI",
    accentColor: "#0f766e",
    backgroundColor: "#f8fafc",
    textColor: "#0f172a",
    borderColor: "#0f766e",
    borderWidth: 3,
    density: "compact",
    showQr: true,
    showNote: false,
    highlightRecipient: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    printMode: "a4",
    sheetLayout: "2x2",
    sizePreset: "100x150",
    labelWidthMm: 100,
    labelHeightMm: 150,
    pageMarginTop: 12,
    pageMarginSide: 12,
    sheetGap: 6,
    logoDataUrl: ""
  },
  receiving: {
    name: "Mal Kabul Etiketi",
    description: "Gelen urun kontrol ve kabul operasyonlari icin net alanlar.",
    brandName: "RECEIVING",
    labelTitle: "MAL KABUL ETIKETI",
    accentColor: "#7c3aed",
    backgroundColor: "#fcfbff",
    textColor: "#2e1065",
    borderColor: "#8b5cf6",
    borderWidth: 2,
    density: "comfortable",
    showQr: true,
    showNote: true,
    highlightRecipient: false,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    printMode: "thermal",
    sheetLayout: "single",
    sizePreset: "a6",
    labelWidthMm: 105,
    labelHeightMm: 148,
    pageMarginTop: 10,
    pageMarginSide: 10,
    sheetGap: 6,
    logoDataUrl: ""
  },
  return: {
    name: "Iade Etiketi",
    description: "Iade urunlerin ayrisma ve geri kabul surecleri icin.",
    brandName: "RETURN",
    labelTitle: "IADE ETIKETI",
    accentColor: "#dc2626",
    backgroundColor: "#ffffff",
    textColor: "#111827",
    borderColor: "#111827",
    borderWidth: 4,
    density: "compact",
    showQr: true,
    showNote: true,
    highlightRecipient: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    printMode: "a4",
    sheetLayout: "3x2",
    sizePreset: "4x6",
    labelWidthMm: 101.6,
    labelHeightMm: 152.4,
    pageMarginTop: 8,
    pageMarginSide: 8,
    sheetGap: 4,
    logoDataUrl: ""
  },
  transfer: {
    name: "Depo Transfer Etiketi",
    description: "Depolar arasi urun hareketleri ve lokasyon transferleri icin.",
    brandName: "TRANSFER",
    labelTitle: "DEPO TRANSFER ETIKETI",
    accentColor: "#1d4ed8",
    backgroundColor: "#f8fbff",
    textColor: "#0f172a",
    borderColor: "#1d4ed8",
    borderWidth: 3,
    density: "compact",
    showQr: true,
    showNote: true,
    highlightRecipient: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    printMode: "a4",
    sheetLayout: "2x2",
    sizePreset: "4x6",
    labelWidthMm: 101.6,
    labelHeightMm: 152.4,
    pageMarginTop: 10,
    pageMarginSide: 10,
    sheetGap: 6,
    logoDataUrl: ""
  },
  pallet: {
    name: "Palet Etiketi",
    description: "Palet takibi, saha sevki ve buyuk hacimli yuklemeler icin.",
    brandName: "PALLET",
    labelTitle: "PALET ETIKETI",
    accentColor: "#0f766e",
    backgroundColor: "#ffffff",
    textColor: "#111827",
    borderColor: "#0f172a",
    borderWidth: 4,
    density: "compact",
    showQr: true,
    showNote: true,
    highlightRecipient: true,
    showOrderNo: true,
    showReference: true,
    showWeight: true,
    showDistance: true,
    showDeliveryTime: true,
    printMode: "a4",
    sheetLayout: "2x2",
    sizePreset: "100x150",
    labelWidthMm: 100,
    labelHeightMm: 150,
    pageMarginTop: 10,
    pageMarginSide: 10,
    sheetGap: 6,
    logoDataUrl: ""
  }
};

export const blankTemplate = {
  name: "Bos Etiket",
  description: "Sifirdan baslamak icin temiz alan.",
  brandName: "",
  labelTitle: "SHIPPING LABEL",
  accentColor: "#f97316",
  backgroundColor: "#ffffff",
  textColor: "#111111",
  borderColor: "#111111",
  borderWidth: 2,
  density: "comfortable",
  showQr: true,
  showNote: true,
  highlightRecipient: false,
  showOrderNo: true,
  showReference: true,
  showWeight: true,
  showDistance: true,
  showDeliveryTime: true,
  printMode: "thermal",
  sheetLayout: "single",
  sizePreset: "4x6",
  labelWidthMm: 101.6,
  labelHeightMm: 152.4,
  pageMarginTop: 12,
  pageMarginSide: 12,
  sheetGap: 8,
  logoDataUrl: ""
};

export const defaultContent = {
  senderName: "S4IN Teknoloji A.S.",
  senderAddress: "Mansuroglu Mah. 286/1 Sok.\nBayrakli / Izmir\nTurkiye 35535",
  recipientName: "Anil Onal",
  recipientAddress: "Ataturk Mah. 1205 Sok. No:15\nBornova / Izmir\n35040 Turkiye",
  orderNo: "S4IN-20260618-000128",
  reference: "INV-20260618-1452",
  weightValue: "2.35",
  weightUnit: "KG",
  distanceValue: "24.5",
  distanceUnit: "KM",
  deliveryTime: "2026-06-18T14:30",
  deliveryType: "Ayni Gun",
  deliveryWindow: "2 Saat Icinde",
  barcodeText: "869123456789012345678901",
  note: "Kargo guvenlige teslim edilebilir."
};

export function buildInitialForm() {
  return {
    templateName: baseTemplates.shipping.name,
    ...baseTemplates.shipping,
    ...defaultContent
  };
}
